export const POST_APPLICATION = "POST_APPLICATION";
export const GET_APPLICATION = "GET_APPLICATION";


export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const MAIN_LOGIN_SUCCESS = "MAIN_LOGIN_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";

export const GET_STUDENTS = "GET_STUDENTS"
export const CLEAR_STUDENTS = "CLEAR_STUDENTS"

export const GET_INSTRUCTORS = "GET_INSTRUCTORS"
export const CLEAR_INSTRUCTORS = "CLEAR_INSTRUCTORS"

export const GET_COURSES = "GET_COURSES"
export const CLEAR_COURSES = "CLEAR_COURSES"

export const GET_SECTIONED_STUDENTS = "GET_SECTIONED_STUDENTS"
export const CLEAR_SECTIONED_STUDENTS = "CLEAR_SECTIONED_STUDENTS"

export const GET_ASSIGNED_COURSES = "GET_ASSIGNED_COURSES"
export const GET_SEMISTERED_COURSES = "GET_SEMISTERED_COURSES"

export const GET_INSTRUCTOR_JOB = "GET_INSTRUCTOR_JOB"

export const GET_INSTRUCTOR_STUDENT_GRADE = "GET_INSTRUCTOR_STUDENT_GRADE"

export const GET_STUDENT_COURSE_REGISTERED = "GET_STUDENTS_COURSE_REGISTERED"

export const SET_TEMPJOB = "SET_TEMPJOB"

export const GET_STUDENT_GRADES = "GET_STUDENT_GRADES"
export const GET_STUDENT_COURSES = "GET_STUDENT_COURSES"

export const GET_ADD_SEMISTER_COURSES = "GET_ADD_SEMISTER_COURSES"
export const GET_ADD_TAKEN_COURSES = "GET_ADD_TAKEN_COURSES"

export const GET_WITHDRAWAL = "GET_WITHDRAWAL"

export const GET_INSTRUCTOR_ASSESSMENT = "GET_INSTRUCTOR_ASSESSMENT"

export const GET_ALL_COURSES = "GET_ALL_COURSES"

export const GET_INSTRUCTOR_MARK = "GET_INSTRUCTOR_MARK"

export const SET_ATTENDANCE_HEADER = "SET_ATTENDANCE_HEADER"

export const SET_MARK_ONLY = "SET_MARK_ONLY"





























